name: Sanity Check

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install modules
        run: yarn

      - name: Lint check
        run: |
          yarn lint:js

      - name: Lint check
        run: |
          yarn test

      - name: Build check
        run: |
          yarn build
